### ISSUE TITLE
'module' object has no attribute 'set_keylog_callback'

### ISSUE THREAD

**Issue by leksito** [segevfiner/sslkeylog#1]
Hi

I'm very interested in that project.
I need to log sslkey on server-side.

I create simple http server
```
import BaseHTTPServer, SimpleHTTPServer

import os
import ssl
import sslkeylog

sslkeylog.set_keylog(os.environ.get('SSLKEYLOGFILE'))

httpd = BaseHTTPServer.HTTPServer(('localhost', 4443), SimpleHTTPServer.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket(httpd.socket, certfile='./server.pem', server_side=True, ssl_version=ssl.PROTOCOL_TLSv1_2)

httpd.serve_forever()
```
and then get error:
```
'module' object has no attribute 'set_keylog_callback'
```

```
$ python --version
Python 2.7.16
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
```

I get the same error when i use python3
```
$ python3 --version
Python 3.7.3
```

**Comment by segevfiner** [comment]
Thanks for trying it out!

The module has a different code path for OpenSSL < 1.1.1 & OpenSSL >= 1.1.1. It looks like the Python part of the module thinks OpenSSL is version 1.1.1 while the compiled C part thinks otherwise.

Try the following to get us some more information:
`python3 -c 'import ssl; print(ssl.OPENSSL_VERSION); print(ssl.OPENSSL_VERSION_INFO)'`

And save `sslversion.c`:
```c
#include <stdio.h>
#include <openssl/ssl.h>

int main(int argc, char *argv[]) {
    printf("OPENSSL_VERSION=%s\n", OPENSSL_VERSION_TEXT);
    printf("OPENSSL_VERSION_NUMBER=0x%.8lx\n", OPENSSL_VERSION_NUMBER);
#if OPENSSL_VERSION_NUMBER >= 0x10101000L
    printf("OpenSSL >= 1.1.1 = true\n");
#else
    printf("OpenSSL >= 1.1.1 = false\n");
#endif

    return 0;
}
```

Build and run it:
```
gcc $(python3-config --cflags --ldflags) -fPIE sslversion.c -o sslversion
./sslversion
```

And post back with the output.

Another possibility is pip caching a version built against OpenSSL <= 1.1.1 and then installing it from the cache when OpenSSL was later upgraded >= 1.1.1 or in a different Python installation that is built agains't a different OpenSSL. You can try `pip install --no-cache-dir --force-reinstall sslkeylog` to reinstall without cache.

**Comment by leksito** [comment]
```
$ python3 -c 'import ssl; print(ssl.OPENSSL_VERSION); print(ssl.OPENSSL_VERSION_INFO)'
OpenSSL 1.1.1b  26 Feb 2019
(1, 1, 1, 2, 15)
```

```
$ ./sslversion 
OPENSSL_VERSION=OpenSSL 1.1.1b  26 Feb 2019
OPENSSL_VERSION_NUMBER=0x1010102f
OpenSSL >= 1.1.1 = true
```
