### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by victorstewart** [segevfiner/sslkeylog#2]
Using Python 3.8... was just about to start experimenting with the library, but getting a segfault everytime I try to run a script.

with this usage..
```
import sslkeylog
sslkeylog.set_keylog("sslkeylog.txt")
```
and this error..
`Segmentation fault: 11`

**Comment by segevfiner** [comment]
Thanks for trying the package!

I'll need more information to be able to reproduce or pinpoint this bug.

* What operating system are you using?
* Can you try reproducing with `faulthandler` enabled? (It's in the standard library, and has a CLI flag)
* Can you try a Python debug build and grab a stack trace using a debugger? (Depends on OS how easy or hard it is to do so)

You can also try `pip install --no-cache-dir --force-reinstall sslkeylog` in case this is caused by a cached build agains't the wrong OpenSSL version.
